sf_image_doctrine:
  class: sfImageTransformRoute
  url:   /thumbnails/:type/:format/:path/:slug-:id.:sf_format
  param: { module: sfImageTransformator, action: index, attribute: file }
  requirements:
    format:    '[\w_-]+(?:,[\w_-]+(?:,[\w_-]+)?)?'
    path:      '[\w/]+'
    slug:      '[\w_-]+'
    id:        '\d+(?:,\d+)?'
    sf_format: 'gif|png|jpg'
    sf_method: [ get ]
  options:
    image_source: Doctrine
    segment_separators: [ '/', '.', '-' ]

sf_image_file:
  class: sfImageTransformRoute
  url:   /thumbnails/:format/:filepath.:sf_format
  param: { module: sfImageTransformator, action: index }
  requirements:
    format:    '[\w_-]+'
    filepath:  '[\w/]+'
    sf_format: 'gif|png|jpg'
    sf_method: [ get ]
  options:
    image_source: File

sf_image_http:
  class: sfImageTransformRoute
  url:   /thumbnails/:format/:protocol/:domain/:filepath.:sf_format
  param: { module: sfImageTransformator, action: index }
  requirements:
    format:    '[\w_-]+'
    sf_format: http|https
    domain:    '[\w-_.]+'
    filepath:  '[\w/-_.]+'
    sf_format: 'gif|png|jpg'
    sf_method: [ get ]
  options:
    image_source: HTTP

sf_image_mock:
  class: sfImageTransformRoute
  url:   /thumbnails/:format.:sf_format
  param: { module: sfImageTransformator, action: index }
  requirements:
    format:    '[\w_-]+'
    sf_format: 'gif|png|jpg'
    sf_method: [ get ]
  options:
    image_source: Mock
